apiVersion: v1
kind: Secret
metadata:
  name: sopas-secrets
  namespace: sopas
type: Opaque
stringData:
  POSTGRES_PASSWORD: sopas
  NEO4J_PASSWORD: sopas123456
  JWT_SECRET: change-me-in-production-k8s
